# Generated by Django 5.2 on 2025-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
