# Generated by Django 5.2 on 2025-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0008_alter_order_contact_alter_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
