# Generated by Django 5.2 on 2025-06-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0010_remove_client_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
