# Generated by Django 5.2 on 2025-06-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0012_alter_client_contact_alter_menu_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
