# Generated by Django 5.2 on 2025-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0002_remove_menu_image_url_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=50, null='edit me'),
            preserve_default='edit me',
        ),
    ]
