# Generated by Django 5.2 on 2025-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0004_client_contact_order_contact_vendor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=50, null=' '),
        ),
    ]
