# Generated by Django 5.2 on 2025-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myrestaurant', '0013_client_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
